### ISSUE TITLE
Wrong description?

### ISSUE THREAD

**Issue by RyuMaster** [xaya/xaya#101]
rpcname.cpp has:

{"address", RPCArg::Type::STR, RPCArg::Optional::NO, "The address to send to."},

should not it be

{"name", RPCArg::Type::STR, RPCArg::Optional::NO, "The nameto send to."},

?

**Comment by domob1812** [comment]
I assume you are talking about `sendtoname`?  Indeed, that seems like a bug in upstream Namecoin.

**Comment by domob1812** [comment]
Fixed upstream in https://github.com/namecoin/namecoin-core/commit/50cd27ebef7f4b18b8793afd650580ef4238020c, which was merged to Xaya's `master` in 1ba84a7cbaac6a2f10ea2e930dffea59149e2efb.
