### ISSUE TITLE
Do we need to use the 1.1 branch to be compatible with the block 440k hardfork?

### ISSUE THREAD

**Issue by DarkClaw1** [xaya/xaya#76]
Ok, after updating my repo and recompiling I see:

```
xxx@xxx:~/xaya$ git log -1
commit 2c638d7734b823c070dd66a17937c012c8e78c43 (HEAD -> master, origin/master, origin/HEAD)
Merge: a79fb687b ce27d9e87
Author: Daniel Kraft <d@domob.eu>
Date:   Wed Dec 5 13:49:39 2018 +0200

    Merge branch 'namecoin'
    
    Updated address format in new wallet_balance.py test.
xxx@xxx:~/xaya$ xayad
2018-12-11T16:26:05Z Xaya version v1.0.3.0-3827a2f80 (release build)
```
Should I have instead checked out the 1.1 branch?

**Comment by domob1812** [comment]
That change in question is not relevant here, but yes, at the moment you should ideally use the `1.1` branch for now.  There is one small change that is present on `1.1` and not yet on `master`, as we are going to merge it to the master branch through upstream repositories (Namecoin in this case).

Eventually `master` will be fine as well, maybe in two weeks or so.

That said, there is not "much" harm in using `master` instead right now - especially if you are not mining.  It is compatible with the hard fork per se.

**Comment by DarkClaw1** [comment]
> That change in question is not relevant here

I meant to only show the status of my xaya repo. 

> That said, there is not "much" harm in using master instead right now - especially if you are not mining. It is compatible with the hard fork per se.

Ok, thanks. I'll use the numbered branches from now on.

**Comment by domob1812** [comment]
> > That change in question is not relevant here
> 
> I meant to only show the status of my xaya repo.

Ah ok.  I thought you were perhaps worried about that "changed address format" in there.  In case you were or someone else is, that is just a change to the unit test and not related to any forks or anything like that at all.

> > That said, there is not "much" harm in using master instead right now - especially if you are not mining. It is compatible with the hard fork per se.
> 
> Ok, thanks. I'll use the numbered branches from now on.

That's certainly the most reasonable choice.  Typically `master` branch should be fine as well, though, the current situation is kind of exceptional.

**Comment by domob1812** [comment]
For the record, since 009decbf9e22fd2cb227f3f1f27723974b640f82 also the `master` branch can be used completely fine again (except of course that it may be unstable).
