### ISSUE TITLE
Instructions to register a name lead to an error

### ISSUE THREAD

**Issue by DarkClaw1** [xaya/xaya#88]
I was trying to learn how to register multiple names to the same address and may have come across a bug. The help for xaya-cli name_register shows this:

```
name_register "name" "value" ("options")

Register a new name.

Arguments:
1. "name"          (string, required) the name to register
2. "value"         (string, required) value for the name
3. "options"       (object, optional)
  {
    "nameEncoding",           (string) Encoding ("ascii", "utf8" or "hex") of the name argument
    "valueEncoding",          (string) Encoding ("ascii", "utf8" or "hex") of the value argument
    "destAddress",            (string) The address to send the name output to
    "sendCoins":              (object) Addresses to which coins should be sent additionally
    {
      "addr1": x,             
      "addr2": y,             
      ...
    }
  }

Result:
"txid"             (string) the name_register's txid

Examples:
> xaya-cli name_register "myname", "new-value"
> xaya-cli name_register "myname", "new-value", "NEX4nME5p3iyNK3gFh4FUeUriHXxEFemo9"
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "name_register", "params": ["myname", "new-value"] }' -H 'content-type: text/plain;' http://127.0.0.1:8336/﻿
```
The first example works fine for me, but not the second:

```
xxx@xxx:~$ xaya-cli name_register "p/abcdefghi", "{}", "CUMknkny8frcxGNT9SEVE5uXXDR5azw43W"
error: Error parsing JSON:CUMknkny8frcxGNT9SEVE5uXXDR5azw43W
```
Also, is this supposed to be the right way to register multiple names to the same address? Does what i am trying to do even make sense?

**Comment by domob1812** [comment]
Good catch, that's indeed a bug - but in the example, not the code itself.  The right way to do it is `destAddress`, so something like this:

    $ xaya-cli name_register p/myname "{}" '{"destAddress":"Cabc..."}'

This is a bug with upstream Namecoin, so we will fix it there.

**Comment by domob1812** [comment]
Actually, that wrong example is not present anymore also in current Xaya Core.  So I guess we can just close this - the next version should not have the faulty example.
